CREATE TABLE board (
    no NUMBER NOT NULL PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    user_id VARCHAR2(40) NOT NULL,
    content VARCHAR2(2000) NOT NULL,
    reg_date Date DEFAULT sysdate NOT NULL,
    upd_date Date DEFAULT sysdate NOT NULL
);

CREATE SEQUENCE SEQ_BOARD
INCREMENT BY 1
START WITH 1
MAXVALUE 100000
MINVALUE 1;